### ISSUE TITLE
Do we want to use a template or are we starting from scratch?

### ISSUE THREAD

**Issue by Nockiro** [nockiro/login-well#1]
If template, which one? If not, we need to discuss the design of the page - not the one of the "toolbar" on the sites we try to login

**Comment by TheLie0** [comment]
💁🏻‍♂

**Comment by Nockiro** [comment]
🤔

**Comment by Nockiro** [comment]
Okay, better question: Are we allowed to use templated? I guess not^^

**Comment by TheLie0** [comment]
I don't think so either. Since we are building the page already, I'm closing this issue.
