### ISSUE TITLE
Create categories

### ISSUE THREAD

**Issue by TheLie0** [nockiro/login-well#15]
Suggestions:

- Kommunikation (Facebook, Twitter, Slack, ..)
- Unterhaltung (Youtube, Netflix, ..)
- Arbeit (Github, ..)

**Comment by Nockiro** [comment]
todo:
- create different top lists with categories
- user as category (with Subcats)

**Comment by Nockiro** [comment]
done with 16d45fdd4e19b6e5d3a02c3b3de112aecba49efb
